from typing import Protocol, Tuple, Optional, Any
from app.domain.models import UserEntity


class KeyCachePort(Protocol):
    """Port for caching parsed public key structures in memory."""
    def get(self, user_id: str) -> Optional[Any]: ...
    def put(self, user_id: str, public_key: Any) -> None: ...
    def invalidate(self, user_id: str) -> None: ...


class SignatureVerifierPort(Protocol):
    """Port for asymmetric and post-quantum signature verification."""
    def verify(self, public_key: Any, payload: bytes, signature: bytes) -> bool: ...
    def parse_public_key(self, public_key_str: str) -> Any: ...
    def get_canonical_key_bytes(self, public_key: Any) -> bytes: ...


class NonceManagerPort(Protocol):
    """Port for sliding replay window validation and atomic state advancement."""
    async def validate_counter(
        self, user_id: str, presented_counter: int
    ) -> Tuple[bool, int, str]: ...
    async def advance_counter(
        self, user_id: str, presented_counter: int
    ) -> Tuple[bool, int, str]: ...
    async def record_sync_nonce(self, user_id: str, sync_nonce: str) -> bool: ...
    async def record_registration_nonce(self, user_id: str, client_nonce: str) -> bool: ...
    async def remove_registration_nonce(self, user_id: str, client_nonce: str) -> None: ...


class UserRepositoryPort(Protocol):
    """Port for persistence and retrieval of identity records."""
    async def get_user_by_id(self, user_id: str) -> Optional[UserEntity]: ...
    async def create_user(self, user: UserEntity) -> None: ...