from typing import Protocol, Tuple, Optional
from cryptography.hazmat.primitives.asymmetric.rsa import RSAPublicKey
from app.domain.models import UserEntity


class KeyCachePort(Protocol):
    """Port for caching parsed public key structures in memory."""
    def get(self, user_id: str) -> Optional[RSAPublicKey]: ...
    def put(self, user_id: str, public_key: RSAPublicKey) -> None: ...
    def invalidate(self, user_id: str) -> None: ...


class SignatureVerifierPort(Protocol):
    """Port for asymmetric signature verification."""
    def verify(self, public_key: RSAPublicKey, payload: bytes, signature: bytes) -> bool: ...
    def parse_public_key(self, public_key_pem: str) -> RSAPublicKey: ...
    def get_canonical_key_bytes(self, public_key: RSAPublicKey) -> bytes: ...


class NonceManagerPort(Protocol):
    """Port for atomic sliding window monotonic counter management and ephemeral nonce tracking."""
    async def validate_and_advance(
        self, user_id: str, presented_counter: int, current_user: Optional[UserEntity] = None
    ) -> Tuple[bool, int, str]: ...
    async def record_sync_nonce(self, user_id: str, sync_nonce: str) -> bool: ...
    async def record_registration_nonce(self, user_id: str, client_nonce: str) -> bool: ...
    async def remove_registration_nonce(self, user_id: str, client_nonce: str) -> None: ...


class UserRepositoryPort(Protocol):
    """Port for persistence and retrieval of identity records."""
    async def get_user_by_id(self, user_id: str) -> Optional[UserEntity]: ...
    async def create_user(self, user: UserEntity) -> None: ...